enum SUCCESS
{
	OK = 200,
	NO_RESPONSE = 204,
	ACCEPTED = 202,
	NO_CONTENT = 204,
	CREATED = 201,
}

enum FAILURE
{
	BAD_REQUEST = 400,
	UNAUTHORIZED = 401,
	FORBIDDEN = 403,
	NOT_FOUND = 404,
	INTERNAL_SERVER_ERROR = 500,
	BAD_GATE_WAY = 503,
}

const SUCCESS_CODES = Object.values(SUCCESS);

const ERROR_CODES = Object.values(FAILURE);

export {SUCCESS_CODES, ERROR_CODES, SUCCESS, FAILURE};